# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ft_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=120)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_match', models.CharField(max_length=200)),
                ('item_brand', models.CharField(max_length=120)),
                ('item_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SecondType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_subtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexCarParty.SecondType'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexCarParty.FirstType'),
        ),
    ]
