# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexCarParty', '0002_auto_20171103_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondtype',
            name='st_ft',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='indexCarParty.FirstType'),
            preserve_default=False,
        ),
    ]
