# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexCarParty', '0003_secondtype_st_ft'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_num',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
